package com.filium.simulation.protocols;

import com.filium.model.network.NetworkTopology;
import com.filium.packet.Packet;
import com.filium.simulation.PacketQueue;
import com.filium.simulation.SimulationEvent;

import java.util.List;

/**
 * Implemented by each protocol handler (ICMP, ARP, DNS, DHCP, HTTP).
 * The SimulationEngine delegates packet processing to the appropriate handler
 * via the ProtocolRegistry.
 */
public interface Protocol {

    /**
     * Returns true if this handler can process the given packet type.
     *
     * @param packet the packet to check; never null
     * @return true if this handler should process the packet
     */
    boolean canHandle(Packet packet);

    /**
     * Processes a packet and returns zero or more response packets
     * that should be enqueued, plus zero or more simulation events
     * that should be emitted.
     *
     * @param packet   the packet to process; never null
     * @param topology the current network topology; never null
     * @param queue    the packet queue for injecting responses; never null
     * @return list of SimulationEvents generated by this interaction
     */
    List<SimulationEvent> handle(Packet packet,
                                 NetworkTopology topology,
                                 PacketQueue queue);
}